In [1]:
from pathlib import Path
import pandas as pd

# 1. BASE DIRECTORY 

BASE = Path.home() / "Desktop" / "LCS_eligibility_Ireland"

CODE_DIR = BASE / "code"
RAW_DIR = BASE / "data_raw"
PROC_DIR = BASE / "data_processed"
OUT_DIR = BASE / "output"

print("Using base directory:", BASE)

Using base directory: C:\Users\tatianabezdenezhnykh\Desktop\LCS_eligibility_Ireland

In [2]:


# Define the file path
file_path = RAW_DIR / "restructured_smoking_population_data.csv"

data = pd.read_csv(file_path)

In [3]:
data.head()

,Statistic Label,Census Year,Sex,Smoking Tobacco Products,Age Group,County,UNIT,VALUE
0,Population,2022,Both Sexes,Smoke daily,All Ages,State,Number,449703.0
1,Population,2022,Both Sexes,Smoke daily,0 - 14 years,State,Number,572.0
2,Population,2022,Both Sexes,Smoke daily,15-19 years,State,Number,8459.0
3,Population,2022,Both Sexes,Smoke daily,20-24 years,State,Number,30998.0
4,Population,2022,Both Sexes,Smoke daily,25-29 years,State,Number,39737.0

In [4]:
# Define the age group mapping
age_group_mapping = {
    '0 - 14 years': '0-14',
    '15-19 years': '15-19',
    '20-24 years': '20-24',
    '25-29 years': '25-29',
    '30-34 years': '30-34',
    '35-39 years': '35-39',
    '40-44 years': '40-44',
    '45-49 years': '45-49',
    '50-54 years': '50-54',
    '55-59 years': '55-59',
    '60-64 years': '60-64',
    '65-69 years': '65-69',
    '70-74 years': '70-74',
    '75-79 years': '75-79',
    '80-84 years': '80-84',
    '85-89 years': '85-89',
    '95 years and over': '90 and over' 
}
# Map age groups in the dataset to the specified categories
data['age_group'] = data['Age Group'].map(age_group_mapping)

In [5]:
# Display unique values for each column except 'VALUE'
unique_values = {col: data[col].unique() for col in data.columns if col != 'VALUE'}

# Displaying the unique values for each column
unique_values

{'Statistic Label': array(['Population'], dtype=object),
 'Census Year': array([2022], dtype=int64),
 'Sex': array(['Both Sexes', 'Male', 'Female'], dtype=object),
 'Smoking Tobacco Products': array(['Smoke daily', 'Smoke occasionally', 'Dont smoke - gave up',
        'Never smoked', 'Not stated'], dtype=object),
 'Age Group': array(['All Ages', '0 - 14 years', '15-19 years', '20-24 years',
        '25-29 years', '30-34 years', '35-39 years', '40-44 years',
        '45-49 years', '50-54 years', '55-59 years', '60-64 years',
        '65-69 years', '70-74 years', '75-79 years', '80-84 years',
        '85-89 years', '95 years and over'], dtype=object),
 'County': array(['State', 'Carlow', 'Dublin City', 'Dun Laoghaire-Rathdown',
        'Fingal', 'South Dublin', 'Kildare', 'Kilkenny', 'Laois',
        'Longford', 'Louth', 'Meath', 'Offaly', 'Westmeath', 'Wexford',
        'Wicklow', 'Clare', 'Cork City', 'Cork County', 'Kerry',
        'Limerick City and County', 'Tipperary',
        'Waterford City and County', 'Galway City', 'Galway County',
        'Leitrim', 'Mayo', 'Roscommon', 'Sligo', 'Cavan', 'Donegal',
        'Monaghan'], dtype=object),
 'UNIT': array(['Number'], dtype=object),
 'age_group': array([nan, '0-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44',
        '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79',
        '80-84', '85-89', '90 and over'], dtype=object)}

In [6]:
# Dropping observations based on specified conditions
filtered_data = data[~(
    (data['Sex'] == 'Both Sexes') |
    (data['County'] == 'State') |
    (data['Age Group'] == 'All Ages')
)]

In [7]:
# Display unique values for each column except 'VALUE'
unique_values = {col: filtered_data[col].unique() for col in data.columns if col != 'VALUE'}

# Displaying the unique values for each column
unique_values

{'Statistic Label': array(['Population'], dtype=object),
 'Census Year': array([2022], dtype=int64),
 'Sex': array(['Male', 'Female'], dtype=object),
 'Smoking Tobacco Products': array(['Smoke daily', 'Smoke occasionally', 'Dont smoke - gave up',
        'Never smoked', 'Not stated'], dtype=object),
 'Age Group': array(['0 - 14 years', '15-19 years', '20-24 years', '25-29 years',
        '30-34 years', '35-39 years', '40-44 years', '45-49 years',
        '50-54 years', '55-59 years', '60-64 years', '65-69 years',
        '70-74 years', '75-79 years', '80-84 years', '85-89 years',
        '95 years and over'], dtype=object),
 'County': array(['Carlow', 'Dublin City', 'Dun Laoghaire-Rathdown', 'Fingal',
        'South Dublin', 'Kildare', 'Kilkenny', 'Laois', 'Longford',
        'Louth', 'Meath', 'Offaly', 'Westmeath', 'Wexford', 'Wicklow',
        'Clare', 'Cork City', 'Cork County', 'Kerry',
        'Limerick City and County', 'Tipperary',
        'Waterford City and County', 'Galway City', 'Galway County',
        'Leitrim', 'Mayo', 'Roscommon', 'Sligo', 'Cavan', 'Donegal',
        'Monaghan'], dtype=object),
 'UNIT': array(['Number'], dtype=object),
 'age_group': array(['0-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44',
        '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79',
        '80-84', '85-89', '90 and over'], dtype=object)}

In [8]:
duplicates_check = data.duplicated(subset=['County', 'Sex', 'Smoking Tobacco Products', 'age_group'])
duplicates_check.any()

False

In [9]:
# Filter for age groups between 50 and 79
age_groups_50_79 = [f"{age}-{age+4}" for age in range(50, 80, 5)]
df_50_79 = filtered_data[filtered_data["age_group"].isin(age_groups_50_79)]

# Calculate total population in each age group
total_by_age_group = df_50_79.groupby("age_group")["VALUE"].sum().reset_index()

# Calculate total population aged 50–79
total_50_79 = total_by_age_group["VALUE"].sum()


total_by_age_group.head()

  age_group     VALUE
0     50-54  340003.0
1     55-59  307165.0
2     60-64  272670.0
3     65-69  238144.0
4     70-74  202884.0

In [10]:
# Map the statuses to simpler terms: Smokers, Quitters, and Never-Smokers
filtered_data['Smoking Tobacco Products'] = filtered_data['Smoking Tobacco Products'].replace({
    'Smoke daily': 'Smokers',
    'Smoke occasionally': 'Smokers',
    'Dont smoke - gave up': 'Quitters',
    'Never smoked': 'Never-Smokers',
    'Not stated': 'Not Stated'
})

C:\Users\tatianabezdenezhnykh\AppData\Local\Temp\ipykernel_24972\2303748828.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Smoking Tobacco Products'] = filtered_data['Smoking Tobacco Products'].replace({

In [11]:
# Dictionary mapping NUTS3 (counties) to NUTS2 regions
# Updated dictionary mapping NUTS3 (counties) to NUTS2 regions
nuts3_to_nuts2 = {
    # Northern & Western NUTS2 Region
    'Cavan': 'Border',
    'Donegal': 'Border',
    'Leitrim': 'Border',
    'Monaghan': 'Border',
    'Sligo': 'Border',
    'Galway City': 'West',
    'Galway County': 'West',
    'Mayo': 'West',
    'Roscommon': 'West',

    # Southern NUTS2 Region
    'Clare': 'Mid-West',
    'Limerick City and County': 'Mid-West',  # fixed spelling
    'Tipperary': 'Mid-West',
    'Carlow': 'South-East',
    'Kilkenny': 'South-East',
    'Waterford City and County': 'South-East',  # fixed spelling
    'Wexford': 'South-East',
    'Cork City': 'South-West',
    'Cork County': 'South-West',
    'Kerry': 'South-West',

    # Eastern & Midland NUTS2 Region
    'Dublin City': 'Dublin',
    'Dun Laoghaire-Rathdown': 'Dublin',  # fixed spelling
    'Fingal': 'Dublin',
    'South Dublin': 'Dublin',
    'Kildare': 'Mid-East',
    'Meath': 'Mid-East',
    'Wicklow': 'Mid-East',
    'Louth': 'Mid-East',
    'Laois': 'Midland',
    'Longford': 'Midland',
    'Offaly': 'Midland',
    'Westmeath': 'Midland'
}

In [12]:
# Add a new column 'NUTS2 Region' based on the 'CSO Local Electoral Areas' (NUTS3 regions)
filtered_data['region'] = filtered_data['County'].map(nuts3_to_nuts2)

# Display the first few rows to confirm the changes
filtered_data.head()

C:\Users\tatianabezdenezhnykh\AppData\Local\Temp\ipykernel_24972\1687520095.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['region'] = filtered_data['County'].map(nuts3_to_nuts2)

,Statistic Label,Census Year,Sex,Smoking Tobacco Products,Age Group,County,UNIT,VALUE,age_group,region
2899,Population,2022,Male,Smokers,0 - 14 years,Carlow,Number,NaN,0-14,South-East
2900,Population,2022,Male,Smokers,15-19 years,Carlow,Number,69.0,15-19,South-East
2901,Population,2022,Male,Smokers,20-24 years,Carlow,Number,270.0,20-24,South-East
2902,Population,2022,Male,Smokers,25-29 years,Carlow,Number,348.0,25-29,South-East
2903,Population,2022,Male,Smokers,30-34 years,Carlow,Number,325.0,30-34,South-East

In [13]:
# Identify counties with missing NUTS2 region mapping
missing_region = filtered_data[filtered_data['region'].isna()]['County'].unique()
print("Counties with missing NUTS2 mapping:", missing_region)

Counties with missing NUTS2 mapping: []

In [14]:
# Filter for age groups between 50 and 79
age_groups_50_79 = [f"{age}-{age+4}" for age in range(50, 80, 5)]
df_50_79 = filtered_data[filtered_data["age_group"].isin(age_groups_50_79)]

# Calculate total population in each age group
total_by_age_group = df_50_79.groupby("age_group")["VALUE"].sum().reset_index()

# Calculate total population aged 50–79
total_50_79 = total_by_age_group["VALUE"].sum()


total_by_age_group.head()
#print(total_50_79)  ###total number CSO projections 1,528,640

  age_group     VALUE
0     50-54  340003.0
1     55-59  307165.0
2     60-64  272670.0
3     65-69  238144.0
4     70-74  202884.0

In [15]:
# Group by region, gender, smoking status, and mapped age group, and sum the population counts
filtered_data = filtered_data.groupby(
    ['region', 'Sex', 'Smoking Tobacco Products', 'age_group']
)['VALUE'].sum().reset_index()

# Filter for age groups between 50 and 79
age_groups_50_79 = [f"{age}-{age+4}" for age in range(50, 80, 5)]
df_50_79 = filtered_data[filtered_data["age_group"].isin(age_groups_50_79)]

# Calculate total population in each age group
total_by_age_group = df_50_79.groupby("age_group")["VALUE"].sum().reset_index()

# Calculate total population aged 50–79
total_50_79 = total_by_age_group["VALUE"].sum()


total_by_age_group.head()

  age_group     VALUE
0     50-54  340003.0
1     55-59  307165.0
2     60-64  272670.0
3     65-69  238144.0
4     70-74  202884.0

In [16]:
# Renaming columns for better clarity and consistency
filtered_data = filtered_data.rename(columns={
    'Sex': 'gender',
    'Smoking Tobacco Products': 'smoking_status',
    'Mapped Age Group': 'age_group',
    'VALUE': 'population'
})

filtered_data.head()

   region  gender smoking_status age_group  population
0  Border  Female  Never-Smokers      0-14     38452.0
1  Border  Female  Never-Smokers     15-19     12065.0
2  Border  Female  Never-Smokers     20-24      7365.0
3  Border  Female  Never-Smokers     25-29      5851.0
4  Border  Female  Never-Smokers     30-34      7118.0

In [17]:
# Convert 'gender', 'smoking_status', and 'age_group' in the smoking dataset to categorical codes

# Gender encoding
filtered_data['gender_code'] = filtered_data['gender'].astype('category').cat.codes

# Smoking status encoding
filtered_data['smoking_status_code'] = filtered_data['smoking_status'].astype('category').cat.codes

# Age group encoding
filtered_data['age_group_code'] = filtered_data['age_group'].astype('category').cat.codes

# Display the first few rows to confirm the encoding
filtered_data.head(40)

,region,gender,smoking_status,age_group,population,gender_code,smoking_status_code,age_group_code
0,Border,Female,Never-Smokers,0-14,38452.0,0,0,0
1,Border,Female,Never-Smokers,15-19,12065.0,0,0,1
2,Border,Female,Never-Smokers,20-24,7365.0,0,0,2
3,Border,Female,Never-Smokers,25-29,5851.0,0,0,3
4,Border,Female,Never-Smokers,30-34,7118.0,0,0,4
5,Border,Female,Never-Smokers,35-39,8158.0,0,0,5
6,Border,Female,Never-Smokers,40-44,8648.0,0,0,6
7,Border,Female,Never-Smokers,45-49,8107.0,0,0,7
8,Border,Female,Never-Smokers,50-54,7353.0,0,0,8
9,Border,Female,Never-Smokers,55-59,7272.0,0,0,9
10,Border,Female,Never-Smokers,60-64,6284.0,0,0,10
11,Border,Female,Never-Smokers,65-69,5568.0,0,0,11
12,Border,Female,Never-Smokers,70-74,5010.0,0,0,12
13,Border,Female,Never-Smokers,75-79,3936.0,0,0,13
14,Border,Female,Never-Smokers,80-84,2871.0,0,0,14
15,Border,Female,Never-Smokers,85-89,2857.0,0,0,15
16,Border,Female,Never-Smokers,90 and over,306.0,0,0,16
17,Border,Female,Not Stated,0-14,3441.0,0,1,0
18,Border,Female,Not Stated,15-19,707.0,0,1,1
19,Border,Female,Not Stated,20-24,613.0,0,1,2
20,Border,Female,Not Stated,25-29,531.0,0,1,3
21,Border,Female,Not Stated,30-34,715.0,0,1,4
22,Border,Female,Not Stated,35-39,804.0,0,1,5
23,Border,Female,Not Stated,40-44,779.0,0,1,6
24,Border,Female,Not Stated,45-49,672.0,0,1,7
25,Border,Female,Not Stated,50-54,640.0,0,1,8
26,Border,Female,Not Stated,55-59,540.0,0,1,9
27,Border,Female,Not Stated,60-64,509.0,0,1,10
28,Border,Female,Not Stated,65-69,481.0,0,1,11
29,Border,Female,Not Stated,70-74,448.0,0,1,12
30,Border,Female,Not Stated,75-79,304.0,0,1,13
31,Border,Female,Not Stated,80-84,236.0,0,1,14
32,Border,Female,Not Stated,85-89,262.0,0,1,15
33,Border,Female,Not Stated,90 and over,46.0,0,1,16
34,Border,Female,Quitters,0-14,321.0,0,2,0
35,Border,Female,Quitters,15-19,378.0,0,2,1
36,Border,Female,Quitters,20-24,652.0,0,2,2
37,Border,Female,Quitters,25-29,1157.0,0,2,3
38,Border,Female,Quitters,30-34,2109.0,0,2,4
39,Border,Female,Quitters,35-39,3426.0,0,2,5

In [18]:
# Filter for age groups between 50 and 79
age_groups_50_79 = [f"{age}-{age+4}" for age in range(50, 80, 5)]
df_50_79 = filtered_data[filtered_data["age_group"].isin(age_groups_50_79)]

# Calculate total population in each age group
total_by_age_group = df_50_79.groupby("age_group")["population"].sum().reset_index()

# Calculate total population aged 50–79
total_50_79 = total_by_age_group["population"].sum()

total_by_age_group.head()
#print(total_50_79)  ###total number CSO projections 1,528,640

  age_group  population
0     50-54    340003.0
1     55-59    307165.0
2     60-64    272670.0
3     65-69    238144.0
4     70-74    202884.0

In [19]:
# Group by relevant categories and sum the population
grouped_data = filtered_data.groupby(['region', 'age_group', 'gender', 'smoking_status']).agg({'population': 'sum'}).reset_index()

# Pivot the data to separate smoking statuses into columns
pivoted_data = grouped_data.pivot_table(
    index=['region', 'age_group', 'gender'],
    columns='smoking_status',
    values='population',
    fill_value=0
).reset_index()

# Calculate total population and percentages for each smoking status
pivoted_data['Total Population'] = pivoted_data.sum(axis=1, numeric_only=True)
pivoted_data['Smokers (%)'] = (pivoted_data.get('Smokers', 0) / pivoted_data['Total Population']) 
pivoted_data['Quitters (%)'] = (pivoted_data.get('Quitters', 0) / pivoted_data['Total Population']) 
pivoted_data['Never-Smokers (%)'] = (pivoted_data.get('Never-Smokers', 0) / pivoted_data['Total Population']) 

# Select and rename columns 
final_data = pivoted_data.rename(
    columns={'Total Population': 'population', 'Smokers (%)': 'smokers', 'Quitters (%)': 'quitters', 'Never-Smokers (%)': 'never_smokers'}
)[['region', 'age_group', 'gender', 'population', 'smokers', 'quitters', 'never_smokers']]

final_data = final_data[~final_data["age_group"].isin(["80-84","85-89", "90 and over", "0 - 14"])].copy()

print(final_data.head(10))

# Print total population for filtered age groups (55-64, 65-74) in merged_data
total_population_filtered = final_data["population"].sum()

print(f"Total population in age groups 55-64 and 65-74: {total_population_filtered:.0f}")

smoking_status  region age_group  gender  population   smokers  quitters  \
0               Border      0-14  Female     42214.0  0.000000  0.007604
1               Border      0-14    Male     44302.0  0.000271  0.004469
2               Border     15-19  Female     13778.0  0.045580  0.027435
3               Border     15-19    Male     14539.0  0.072770  0.033978
4               Border     20-24  Female     10332.0  0.164731  0.063105
5               Border     20-24    Male     11169.0  0.240666  0.072254
6               Border     25-29  Female      9483.0  0.204998  0.122008
7               Border     25-29    Male      9705.0  0.311901  0.116950
8               Border     30-34  Female     12056.0  0.175348  0.174934
9               Border     30-34    Male     11000.0  0.280455  0.157364

smoking_status  never_smokers
0                    0.910883
1                    0.916505
2                    0.875671
3                    0.845313
4                    0.712834
5                    0.622258
6                    0.616999
7                    0.502628
8                    0.590411
9                    0.489727

Total population in age groups 55-64 and 65-74: 4966136

In [20]:
file_path = PROC_DIR / "cleaned_smoking_data.csv"
final_data.to_csv(file_path, index=False)

final_data.head()

smoking_status,region,age_group,gender,population,smokers,quitters,never_smokers
0,Border,0-14,Female,42214.0,0.000000,0.007604,0.910883
1,Border,0-14,Male,44302.0,0.000271,0.004469,0.916505
2,Border,15-19,Female,13778.0,0.045580,0.027435,0.875671
3,Border,15-19,Male,14539.0,0.072770,0.033978,0.845313
4,Border,20-24,Female,10332.0,0.164731,0.063105,0.712834

In [21]:
# Filter for age groups between 50 and 79
age_groups_50_79 = [f"{age}-{age+4}" for age in range(50, 80, 5)]
df_50_79 = final_data[final_data["age_group"].isin(age_groups_50_79)]

# Calculate total population in each age group
total_by_age_group = df_50_79.groupby("age_group")["population"].sum().reset_index()

# Calculate total population aged 50–79
total_50_79 = total_by_age_group["population"].sum()


print(total_50_79)  ###total number CSO projections 1,528,640

1515126.0

In [22]:
total_by_age_group.head()

  age_group  population
0     50-54    340003.0
1     55-59    307165.0
2     60-64    272670.0
3     65-69    238144.0
4     70-74    202884.0

	age_group	population
0	50-54	342879
1	55-59	309744
2	60-64	275834
3	65-69	240482
4	70-74	204684

In [23]:
# Display unique values for each column except 'VALUE'
unique_values = {col: final_data[col].unique() for col in final_data.columns if col != 'VALUE'}

# Displaying the unique values for each column
unique_values

{'region': array(['Border', 'Dublin', 'Mid-East', 'Mid-West', 'Midland',
        'South-East', 'South-West', 'West'], dtype=object),
 'age_group': array(['0-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44',
        '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79'],
       dtype=object),
 'gender': array(['Female', 'Male'], dtype=object),
 'population': array([ 42214.,  44302.,  13778.,  14539.,  10332.,  11169.,   9483.,
          9705.,  12056.,  11000.,  14833.,  13626.,  16149.,  15276.,
         14972.,  14699.,  14089.,  14279.,  13361.,  13139.,  12304.,
         11979.,  10975.,  11107.,   9411.,   9538.,   7210.,   7111.,
        131090., 137489.,  43685.,  44304.,  50643.,  48921.,  55409.,
         54570.,  59696.,  57155.,  61366.,  58328.,  61215.,  59256.,
         51550.,  50718.,  45307.,  44280.,  40456.,  37879.,  35683.,
         33126.,  30885.,  27590.,  26644.,  23308.,  20912.,  17460.,
         80057.,  84467.,  26525.,  27930.,  20719.,  22703.,  18967.,
         18622.,  23993.,  21572.,  30422.,  27073.,  33313.,  31080.,
         30141.,  29413.,  26452.,  26781.,  22718.,  22653.,  19012.,
         18770.,  16321.,  15829.,  13790.,  13084.,  10435.,   9773.,
         47766.,  49841.,  16410.,  17295.,  14385.,  15020.,  13168.,
         13232.,  14875.,  13983.,  18282.,  16598.,  19700.,  18654.,
         18275.,  18253.,  16984.,  17132.,  15924.,  15915.,  14417.,
         14508.,  12794.,  13109.,  11333.,  11117.,   8857.,   8179.,
         32470.,  34331.,  10632.,  11469.,   8366.,   9097.,   7991.,
          8026.,   9749.,   9066.,  12353.,  11375.,  13107.,  12451.,
         11574.,  11609.,  10514.,  10833.,   9510.,   9588.,   8393.,
          8577.,   7355.,   7440.,   6061.,   6170.,   4830.,   4428.,
         43939.,  46094.,  15028.,  15968.,  11886.,  12808.,  11460.,
         11159.,  13614.,  12760.,  16759.,  14814.,  18231.,  17249.,
         16986.,  16405.,  15670.,  15556.,  14984.,  14557.,  13373.,
         12997.,  11394.,  11519.,   9763.,   9737.,   7730.,   7325.,
         69899.,  72385.,  23449.,  24583.,  21295.,  21702.,  19894.,
         19963.,  23277.,  21592.,  27967.,  25277.,  30051.,  28436.,
         27148.,  26962.,  24781.,  25011.,  23120.,  23148.,  20870.,
         20637.,  18218.,  18031.,  15714.,  15490.,  12426.,  11478.,
         45719.,  48248.,  15779.,  16254.,  14071.,  14026.,  12038.,
         12121.,  14446.,  13389.,  17675.,  16121.,  19197.,  18159.,
         17684.,  17115.,  16213.,  15193.,  14187.,  13837.,  12820.,
         12757.,  10887.,  10837.,   8134.,   7972.]),
 'smokers': array([0.00000000e+00, 2.70868132e-04, 4.55799100e-02, 7.27697916e-02,
        1.64730933e-01, 2.40666129e-01, 2.04998418e-01, 3.11901082e-01,
        1.75348374e-01, 2.80454545e-01, 1.64835165e-01, 2.47174519e-01,
        1.54189114e-01, 2.20803875e-01, 1.48343575e-01, 2.02734880e-01,
        1.53736958e-01, 1.90909728e-01, 1.42279769e-01, 1.78932948e-01,
        1.36784785e-01, 1.54436931e-01, 1.22095672e-01, 1.33699469e-01,
        9.75454256e-02, 1.07989096e-01, 9.01525659e-02, 9.21108142e-02,
        1.45466183e-04, 5.00629507e-02, 6.83911159e-02, 1.62470628e-01,
        2.29635535e-01, 1.76000289e-01, 2.74528129e-01, 1.60747789e-01,
        2.43810690e-01, 1.51256396e-01, 2.26066383e-01, 1.44115004e-01,
        2.11759147e-01, 1.44694471e-01, 1.98903742e-01, 1.58032975e-01,
        1.98915989e-01, 1.63090765e-01, 1.91874126e-01, 1.59235490e-01,
        1.74334360e-01, 1.44244779e-01, 1.43892715e-01, 1.12633238e-01,
        1.16526515e-01, 8.48316756e-02, 8.31042383e-02, 2.12348702e-04,
        1.77584145e-04, 4.59189444e-02, 6.56999642e-02, 1.61446016e-01,
        2.36708805e-01, 1.91912269e-01, 2.91483192e-01, 1.78927187e-01,
        2.67476358e-01, 1.66721452e-01, 2.46149300e-01, 1.48560622e-01,
        2.21750322e-01, 1.45283833e-01, 1.95219801e-01, 1.50234387e-01,
        1.86960905e-01, 1.47460164e-01, 1.75164437e-01, 1.46276036e-01,
        1.58817262e-01, 1.30322897e-01, 1.33299640e-01, 1.08556925e-01,
        1.08758789e-01, 8.45232391e-02, 8.38023125e-02, 1.25612360e-04,
        5.11882998e-02, 6.88060133e-02, 1.71289538e-01, 2.35419441e-01,
        2.07852369e-01, 2.86653567e-01, 1.85680672e-01, 2.74118573e-01,
        1.81325894e-01, 2.55030727e-01, 1.66649746e-01, 2.22794039e-01,
        1.59452804e-01, 2.09445023e-01, 1.62623646e-01, 2.01961242e-01,
        1.63149962e-01, 1.73358467e-01, 1.56204481e-01, 1.59498208e-01,
        1.28028763e-01, 1.29758181e-01, 1.07561987e-01, 1.04074840e-01,
        8.45658801e-02, 8.17948404e-02, 5.10722348e-02, 7.55950824e-02,
        1.68419794e-01, 2.48213697e-01, 2.16243274e-01, 3.10740095e-01,
        2.11508873e-01, 2.83366424e-01, 1.87808629e-01, 2.60219780e-01,
        1.71892882e-01, 2.36848446e-01, 1.63297045e-01, 2.19140322e-01,
        1.72341640e-01, 2.16098957e-01, 1.64773922e-01, 1.91072174e-01,
        1.61086620e-01, 1.69872916e-01, 1.33514616e-01, 1.42607527e-01,
        1.07902986e-01, 1.14262561e-01, 8.88198758e-02, 8.71725384e-02,
        1.73558381e-04, 4.97072132e-02, 7.32089178e-02, 1.86101296e-01,
        2.60618364e-01, 2.18586387e-01, 3.13558563e-01, 2.01410313e-01,
        2.78761755e-01, 1.86765320e-01, 2.61914405e-01, 1.74866985e-01,
        2.39782016e-01, 1.65018250e-01, 2.15848827e-01, 1.71155073e-01,
        2.08536899e-01, 1.61105179e-01, 1.87195164e-01, 1.54639946e-01,
        1.67269370e-01, 1.27172196e-01, 1.33258095e-01, 1.02632388e-01,
        1.08246893e-01, 7.77490298e-02, 8.39590444e-02, 5.32645315e-02,
        7.16348696e-02, 1.81873679e-01, 2.50668141e-01, 2.05288027e-01,
        2.94895557e-01, 1.77600206e-01, 2.70007410e-01, 1.69556978e-01,
        2.43541560e-01, 1.53572260e-01, 2.12195808e-01, 1.44209518e-01,
        1.97500185e-01, 1.54513539e-01, 1.87637440e-01, 1.45934256e-01,
        1.69517885e-01, 1.40488740e-01, 1.44303920e-01, 1.21034142e-01,
        1.30164716e-01, 9.06834670e-02, 9.65138799e-02, 6.93706744e-02,
        7.64070396e-02, 1.86536229e-04, 5.64040814e-02, 7.16131414e-02,
        1.86482837e-01, 2.65150435e-01, 1.99700947e-01, 3.06657867e-01,
        1.81157414e-01, 2.69400254e-01, 1.61244696e-01, 2.39811426e-01,
        1.45231026e-01, 2.07169998e-01, 1.38599864e-01, 2.00408998e-01,
        1.44266946e-01, 1.84914087e-01, 1.34338182e-01, 1.62982690e-01,
        1.39987312e-01, 1.51188842e-01, 1.12402496e-01, 1.17896057e-01,
        9.85579131e-02, 1.00027683e-01, 7.67150234e-02, 8.31660813e-02]),
 'quitters': array([0.00760411, 0.00446932, 0.02743504, 0.03397758, 0.06310492,
        0.07225356, 0.1220078 , 0.11695003, 0.17493364, 0.15736364,
        0.23097148, 0.20893879, 0.26205957, 0.2470542 , 0.26529522,
        0.27716171, 0.27894102, 0.31402759, 0.27303346, 0.31729964,
        0.31111834, 0.35445363, 0.3267426 , 0.41397317, 0.32249495,
        0.43960998, 0.32177531, 0.47321052, 0.00491266, 0.00637869,
        0.02112853, 0.02676959, 0.05611832, 0.06704687, 0.09819704,
        0.11040865, 0.14706178, 0.15088794, 0.19693316, 0.19753806,
        0.22793433, 0.23285406, 0.24506305, 0.26018376, 0.25750988,
        0.27901987, 0.27115879, 0.30225191, 0.29890985, 0.33722756,
        0.32264853, 0.3901776 , 0.31515538, 0.42101424, 0.31350421,
        0.46254296, 0.00279801, 0.0078137 , 0.02495759, 0.02663802,
        0.06670206, 0.07056336, 0.12664101, 0.12759102, 0.1842204 ,
        0.17666419, 0.24038525, 0.2236915 , 0.26776334, 0.26943372,
        0.26883647, 0.28759392, 0.28039468, 0.31432732, 0.28127476,
        0.32794773, 0.30265096, 0.36547682, 0.32442865, 0.40539516,
        0.31312545, 0.43274228, 0.30167705, 0.47498209, 0.00487795,
        0.00808571, 0.02626447, 0.03035559, 0.0684741 , 0.0741012 ,
        0.12234204, 0.12401753, 0.18023529, 0.16441393, 0.23099223,
        0.2117725 , 0.25436548, 0.24686394, 0.27004104, 0.27940613,
        0.2787918 , 0.30807845, 0.27744285, 0.32051524, 0.30443227,
        0.34946237, 0.31811787, 0.39186818, 0.3008912 , 0.42709364,
        0.30518234, 0.45470106, 0.00461965, 0.00559261, 0.02793454,
        0.03295841, 0.06849151, 0.0771683 , 0.13615317, 0.12048343,
        0.18104421, 0.16666667, 0.23581316, 0.2116044 , 0.24505989,
        0.24046261, 0.26213928, 0.27340856, 0.27325471, 0.3014862 ,
        0.26635121, 0.32133917, 0.30120338, 0.35828378, 0.31883073,
        0.39596774, 0.29879558, 0.42301459, 0.27784679, 0.45325203,
        0.00557591, 0.00405693, 0.02934522, 0.03294088, 0.07529867,
        0.08221424, 0.13446771, 0.12859575, 0.1933304 , 0.17805643,
        0.23843905, 0.2217497 , 0.26954089, 0.25885559, 0.28011303,
        0.29320329, 0.29355456, 0.31344819, 0.29538174, 0.33447826,
        0.31728109, 0.36608448, 0.3232403 , 0.41791822, 0.30216122,
        0.4354524 , 0.29262613, 0.45365188, 0.00640925, 0.00762589,
        0.02716534, 0.03046821, 0.06724583, 0.07478573, 0.11908113,
        0.11952111, 0.1791468 , 0.1663116 , 0.23724389, 0.22447284,
        0.27177132, 0.25742017, 0.27556358, 0.29267117, 0.28876962,
        0.32369757, 0.28213668, 0.33359253, 0.30177288, 0.36046906,
        0.31018773, 0.38633465, 0.29387807, 0.42537121, 0.28593272,
        0.45138526, 0.00673681, 0.00688111, 0.02332214, 0.03168451,
        0.06182929, 0.07657208, 0.11729523, 0.11970959, 0.1745812 ,
        0.1693181 , 0.23287129, 0.21518516, 0.27478252, 0.26312022,
        0.28183669, 0.29085597, 0.28458644, 0.32386328, 0.28032647,
        0.32989348, 0.30725312, 0.36178362, 0.32574103, 0.41208748,
        0.32010655, 0.43360709, 0.3240718 , 0.46512795]),
 'never_smokers': array([0.91088265, 0.9165049 , 0.87567136, 0.84531261, 0.71283391,
        0.62225804, 0.61699884, 0.50262751, 0.59041141, 0.48972727,
        0.54998989, 0.48334067, 0.53551303, 0.47289866, 0.54147742,
        0.46819512, 0.52189652, 0.44386862, 0.54427064, 0.46198341,
        0.51072822, 0.44678187, 0.50733485, 0.41037184, 0.53235575,
        0.40742294, 0.54590846, 0.40036563, 0.86727439, 0.86154529,
        0.83055969, 0.80213976, 0.69279071, 0.59780054, 0.64650147,
        0.52327286, 0.59808027, 0.49773423, 0.55320536, 0.46382526,
        0.53315364, 0.44211557, 0.52407371, 0.4385031 , 0.50802304,
        0.42809395, 0.49718212, 0.42477362, 0.47524031, 0.41007064,
        0.46660191, 0.39140993, 0.50142621, 0.38900807, 0.52845256,
        0.38424971, 0.92008194, 0.91319687, 0.8796607 , 0.85918367,
        0.71649211, 0.6299608 , 0.62672009, 0.51498228, 0.58400367,
        0.49137771, 0.54279798, 0.47157685, 0.53627713, 0.45170528,
        0.54069208, 0.46567844, 0.5279374 , 0.44897502, 0.53024034,
        0.44881473, 0.50683779, 0.4274374 , 0.50070461, 0.41310253,
        0.52864394, 0.40973708, 0.55783421, 0.38749616, 0.89015199,
        0.88766277, 0.85393053, 0.83162764, 0.67521724, 0.60938748,
        0.58573815, 0.49720375, 0.53902521, 0.4584853 , 0.49556941,
        0.4306543 , 0.49441624, 0.43776134, 0.50183311, 0.43220293,
        0.49505417, 0.41787299, 0.50156996, 0.44115614, 0.48130679,
        0.42748828, 0.49726434, 0.41749943, 0.531898  , 0.41171179,
        0.55120244, 0.40396136, 0.89433323, 0.89394425, 0.85430775,
        0.82212922, 0.67463543, 0.57788282, 0.56025529, 0.46860204,
        0.52323315, 0.43834105, 0.50125476, 0.43542857, 0.51857786,
        0.43562766, 0.51296008, 0.4373331 , 0.49448355, 0.41548971,
        0.51388013, 0.42782645, 0.48397474, 0.41401422, 0.48851122,
        0.40228495, 0.52681076, 0.40226904, 0.56501035, 0.4035682 ,
        0.90746262, 0.9082527 , 0.86485228, 0.83748747, 0.67482753,
        0.58471268, 0.58420593, 0.48158437, 0.53812252, 0.46324451,
        0.51023331, 0.44457945, 0.49722999, 0.43457592, 0.50412104,
        0.43370923, 0.48978941, 0.42568784, 0.50233582, 0.4294841 ,
        0.48366111, 0.41578826, 0.49982447, 0.40593802, 0.53969067,
        0.40340967, 0.56843467, 0.40914676, 0.91364683, 0.90991227,
        0.86728645, 0.84054021, 0.69528058, 0.60584278, 0.61465769,
        0.51485248, 0.57692142, 0.48721749, 0.5288018 , 0.45721407,
        0.51692123, 0.45769447, 0.53189922, 0.44937319, 0.50946289,
        0.4343289 , 0.52750865, 0.44612926, 0.51106852, 0.44376605,
        0.52129762, 0.4369142 , 0.56408298, 0.42537121, 0.58586834,
        0.41775571, 0.90476607, 0.90320842, 0.86380632, 0.83788606,
        0.67919835, 0.58320262, 0.61231102, 0.49674119, 0.56811574,
        0.47509149, 0.54036775, 0.47155884, 0.51956035, 0.45756925,
        0.52827415, 0.44633363, 0.51958305, 0.43458843, 0.53827421,
        0.45705726, 0.50475788, 0.43593264, 0.51131045, 0.42266991,
        0.52815284, 0.41358309, 0.54229162, 0.40203211])}

In [24]:


final_data_ag = (
    final_data
    .groupby(["age_group", "gender"], as_index=False)  # Group by age_group and gender
    .agg({
        "population": "sum",  # Sum populations
        "smokers": lambda x: (x * final_data.loc[x.index, "population"]).sum() / final_data.loc[x.index, "population"].sum(),
        "quitters": lambda x: (x * final_data.loc[x.index, "population"]).sum() / final_data.loc[x.index, "population"].sum(),
        "never_smokers": lambda x: (x * final_data.loc[x.index, "population"]).sum() / final_data.loc[x.index, "population"].sum()
    })
)

# Inspect the final aggregated DataFrame
print(final_data_ag.head())

# Print total population for filtered age groups (55-64, 65-74) in merged_data
total_population_filtered = final_data_ag["population"].sum()

print(f"Total population in age groups 55-64 and 65-74: {total_population_filtered:.0f}")

smoking_status age_group  gender  population   smokers  quitters  \
0                   0-14  Female    493154.0  0.000047  0.005217
1                   0-14    Male    517157.0  0.000124  0.006576
2                  15-19  Female    165286.0  0.050228  0.025029
3                  15-19    Male    172342.0  0.070058  0.029691
4                  20-24  Female    151697.0  0.170452  0.063488

smoking_status  never_smokers
0                    0.897207
1                    0.894177
2                    0.857550
3                    0.831440
4                    0.692407
Total population in age groups 55-64 and 65-74: 4966136

In [25]:


file_path = PROC_DIR / "cleaned_smoking_data_ag.csv"
final_data_ag.to_csv(file_path, index=False)